eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseExpirationDurationInSeconds: 4  
    leaseRenewalIntervalInSeconds: 1  
spring:
  application:
    name: ribbon-consumer-hystrix

server:
  port: 9002

url: http://localhost:9002/sendMsg