spring:
  application:
    name: zuul-service

server:
  port: 9011

#zuul:
#  routes:
#    blog:
#        path: /ymq/**
#        url: http://www.baidu.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api:
        path: /**
        serviceId: eureka-provider
