spring:
  application:
    name: zuul-service-filter

server:
  port: 9010

zuul:
  routes:
    api:
        path: /**
        serviceId: eureka-provider

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseExpirationDurationInSeconds: 4  
    leaseRenewalIntervalInSeconds: 1  
