eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseExpirationDurationInSeconds: 4  
    leaseRenewalIntervalInSeconds: 1  
spring:
  application:
    name: ribbon-consumer-hystrix

server:
  port: 9005
#用于存入本地文件，供ReadLocalProperties项目读取并调用
url: http://localhost:9005/sendMsg